//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoinLoad
    {
        public int Id { get; set; }
        public short Cnt { get; set; }
        public int CoinTypeId { get; set; }
        public int OperationId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual CoinType CoinType { get; set; }
        public virtual Operation Operation { get; set; }
    }
}
