//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myEntities : DbContext
    {
        public myEntities()
            : base("name=myEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CoinLoad> CoinLoads { get; set; }
        public DbSet<CoinType> CoinTypes { get; set; }
        public DbSet<Operation> Operations { get; set; }
        public DbSet<OrderCoin> OrderCoins { get; set; }
        public DbSet<OrderProd> OrderProds { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<ProdLoad> ProdLoads { get; set; }
        public DbSet<Product> Products { get; set; }
    }
}
