//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderCoins = new HashSet<OrderCoin>();
            this.OrderProds = new HashSet<OrderProd>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<OrderCoin> OrderCoins { get; set; }
        public virtual ICollection<OrderProd> OrderProds { get; set; }
    }
}
