//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderProds = new HashSet<OrderProd>();
            this.ProdLoads = new HashSet<ProdLoad>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual ICollection<OrderProd> OrderProds { get; set; }
        public virtual ICollection<ProdLoad> ProdLoads { get; set; }
    }
}
