//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSet
    {
        public int Id { get; set; }
        public DateTime PurchaseDate { get; set; }
        public decimal Amount { get; set; }
        public int ManagerId { get; set; }
        public int CustomerId { get; set; }
        public int ProductId { get; set; }
    
        public virtual CustomerSet CustomerSet { get; set; }
        public virtual ManagerSet ManagerSet { get; set; }
        public virtual ProductSet ProductSet { get; set; }
    }
}
