//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string LinkId { get; set; }
        public string Advertiser { get; set; }
        public string Link { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public int SubCategorieId { get; set; }
    
        public virtual SubCategorie SubCategorie { get; set; }
    }
}
